spring.application.name=irummate

# spring boot .env?(?? ? ??)
spring.config.import=optional:file:.env[.properties]

# PostgreSQL ??
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

# kakao
kakao.client-id=${KAKAO_CLIENT_ID}
kakao.client-secret=${KAKAO_CLIENT_SECRET}
kakao.redirect-uri=${KAKAO_REDIRECT_URI}

#security
logging.level.org.springframework.security=DEBUG

jwt.secret=${JWT_SECRET}


# S3
cloud.aws.s3.bucket=irummate-s3-bucket
cloud.aws.region=ap-northeast-2