spring.application.name=irummate

# spring boot .env?(?? ? ??)
spring.config.import=optional:file:.env[.properties]

# PostgreSQL ??
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# kakao
kakao.client-id=${KAKAO_CLIENT_ID}
kakao.client-secret=${KAKAO_CLIENT_SECRET}
kakao.redirect-uri=${KAKAO_REDIRECT_URI}

#security
logging.level.org.springframework.security=DEBUG

jwt.secret=${JWT_SECRET}

# aws s3
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
aws.s3.region=${AWS_S3_REGION}
aws.credentials.access-key-id=${AWS_ACCESS_KEY_ID}
aws.credentials.secret-access-key=${AWS_SECRET_ACCESS_KEY}
aws.credentials.session-token=${AWS_SESSION_TOKEN:}
